### get products
GET http://localhost:1337/products

### auth
POST http://localhost:1337/auth/local
Content-Type: application/json

{
  "identifier": "alice@example.com",
  "password": "Alice123"
}

### api login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "Alice123"
}

### register user
POST http://localhost:1337/auth/local/register
Content-Type: application/json

{
  "username": "Charlie",
  "email": "charlie@example.com",
  "password": "Charlie123"
}

### get cart items
GET http://localhost:1337/cart-items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgyMzY2OTQxLCJleHAiOjE2ODQ5NTg5NDF9.OqLrD8WRRf-tryrn4vZfF0GRhj_mX5HjV3gfx4ec7pg

### post cart items
POST http://localhost:1337/cart-items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgyMzY2OTQxLCJleHAiOjE2ODQ5NTg5NDF9.OqLrD8WRRf-tryrn4vZfF0GRhj_mX5HjV3gfx4ec7pg
Content-Type: application/json

{
  "product": 2,
  "quantity": 1
}

### post cart items by api
POST http://localhost:3000/api/cart
Content-Type: application/json

{
  "productId": 2,
  "quantity": 1
}

### get cart by api
GET http://localhost:3000/api/cart

### get user
GET http://localhost:1337/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxNDc4ODYzLCJleHAiOjE2ODQwNzA4NjN9.YO24MQnlhBTbNrbLKzwdmRVRKpOwZpESx2KQ8TZ9Hgo

### get user by api
GET http://localhost:3000/api/user
